name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin
      - name: Build and push images
        run: |
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest ./apps/backend
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/backend:latest
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/signaling:latest ./apps/signaling
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/signaling:latest
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/media:latest ./apps/media
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/media:latest
